#Conexion a sql server de Docker
spring.datasource.url=jdbc:sqlserver://db-poo:1433;databaseName=BIBLIOTECA;encrypt=false;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=Proyecto123#
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

#Esto evita que Hibernate intente modificar o borrar tus tablas 
spring.jpa.hibernate.ddl-auto=none

#Muestra en la terminal las consultas SQL reales que Spring hace por debajo (util para el debug ya que hay mucho vibe coding)
spring.jpa.show-sql=true

# Obliga a Hibernate a usar los nombres de las columnas sin calmelcase en @Column (un dolor de webos que me dio esta mmda)
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl